create table if not exists public.webapp_action_logs (
  id bigint generated by default as identity primary key,
  actor_name text not null default 'System',
  action text not null,
  target_type text not null default 'webapp',
  target_id text,
  target_name text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists webapp_action_logs_created_at_idx
  on public.webapp_action_logs (created_at desc, id desc);

create index if not exists webapp_action_logs_target_idx
  on public.webapp_action_logs (target_type, target_id);

alter table public.webapp_action_logs enable row level security;

revoke all on table public.webapp_action_logs from anon, authenticated;
revoke all on sequence public.webapp_action_logs_id_seq from anon, authenticated;

